version: '3.8'
services:
  app:
    build: .
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
