version: '3.8'
services:
  app:
    build: .
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
  worker:
    build: .
    command: ["python", "run_worker.py"]
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
